name: gestao_restaurante
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.2
  equatable: ^2.0.5
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_gutter: ^1.0.2
  flutter_localizations:
    sdk: flutter
  form_builder_image_picker: ^4.0.0
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
